name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Server
    steps:
      - name: 📂 Заливаем файлы на сервер
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PURESERVER_HOST }}
          username: ${{ secrets.PURESERVER_USER }}
          key: ${{ secrets.PURESERVER_PRIVATE }}
          script: cd /srv/laravel-app && sh deploy.sh
